<?php

const
DEVICE_CONFIG 	= 'config',
DEVICE_INFO	  	= 'info',
DEVICE_ICONS  	= 'icons',
DEVICE_SERVICES	= 'services',
DEVICE_KEYCODES	= 'keycodes',
DEVICE_DESCRIPTIONS='descriptions';

const
INFO_NAME		= 'name',
INFO_TYPE		= 'type',
INFO_MANU_FACT	= 'manufacturer',
INFO_MANU_URL	= 'manuurl',
INFO_DESC		= 'desc',
INFO_MODEL_NAME	= 'modelname',
INFO_MODEL_NR	= 'modelnr',
INFO_MODEL_URL	= 'modelurl',
INFO_SERIAL		= 'serial',
INFO_UDN		= 'udn',
INFO_MANU_ID	= 'manu_id', 
INFO_MODEL_ID	= 'model_id',
INFO_VERSION    = 'version';

const
ICON_MIME		= 'mime',
ICON_WIDTH		= 'width',
ICON_HEIGHT		= 'height',
ICON_DEPTH		= 'depth',
ICON_URL		= 'url';


const
CONFIG_SCHEME	= '_scheme',
CONFIG_HOST		= '_host',
CONFIG_PORT		= '_port',
CONFIG_OPTIONS	= 'options',
//	CONFIG_CRYPTED  = 'crypted',
CONFIG_CONNECTION_TYPE 	= 'contype',
CONFIG_CREDITIALS  = 'credits',
CONFIG_PROPS_OPTIONS = 'props',
CONFIG_PROPS_GROUPS = 'groups';

const
CREDIT_USER		= 'user',
CREDIT_PASS		= 'pass',
CREDIT_CAFILE   = 'cafile';

const
SERVICE_NAME		= 'name',
SERVICE_ID			= 'id',
SERVICE_CTRL_URL	= 'ctrlurl',
SERVICE_EVENT_URL 	= 'eventurl',
SERVICE_PORT		= 'port',
SERVICE_FUNCTIONS 	= 'funcs',
SERVICE_CONNECTION_TYPE ='contype',
SERVICE_DESC_ID		= 'desc',
SERVICE_FILTER_DEF	= 'filter',
SERVICE_LOWER_NAMES	= 'lowernames';

const
FUNCTION_NAME		= 'name',
FUNCTION_PARAMS		= 'params',
FUNCTION_DESC_ID	= 'desc',
FUNCTION_EVENTS		= 'events',
FUNCTION_SOURCE		= 'source';

const
PARAM_IN 		= 'in',
PARAM_OUT 		= 'out';

const
VALUE_DEFAULT   = 'default',
VALUE_MIN		= 'min',
VALUE_MAX		= 'max',
VALUE_STEP		= 'step',
VALUE_LIST		= 'list',
VALUE_TYPE		= 'type',
VALUE_NAME		= 'name',
VALUE_DESC_ID	= 'desc';

const
DATATYPE_BOOL	= 'bool',
DATATYPE_INT	= 'int',
DATATYPE_UINT	= 'uint',
DATATYPE_FLOAT	= 'float',
DATATYPE_STRING	= 'string',
DATATYPE_ARRAY  = 'array',
DATATYPE_OBJECT = 'object',
DATATYPE_MIXED  = 'mixed',
DATATYPE_BYTE	= 'byte',
DATATYPE_UNKNOWN= 'unknown';

const 
PREDEF_DETECTION= 'detection',
PREDEF_ITEMS	= 'items',
PREDEF_MODELS 	= 'models',
PREDEF_KEYCODES = 'codes',
KEYFUNC_PARAMS  = 'params',
KEYFUNC_SOURCE 	= 'source',
DETECTION_MANU  = 'manu_detect',
DETECTION_MODEL = 'model_detect';



?>