<?php
const 
	ERR_EmptyResponse  			= 8601,
	ERR_MethodNoScala			= 8602,
	ERR_FormatArray         	= 8603,
	ERR_InvalidResponceFormat 	= 8604,
	ERR_NoResponseID			= 8605,
	ERR_InvalidResponseID		= 8606,
	ERR_InvalidResposeCode		= 8607,
	ERR_InvalidResposeSID		= 8608,
	
	ERR_DeviceHasNoKeyCodes		= 8700,
	ERR_DeviceCantSendKeyCodes	= 8701,
	ERR_KeyCodeNotExists		= 8702,
	ERR_CantGetLocalIP			= 8703,
	
	ERR_SubFileNotFound         = 8900,
	ERR_NotInCacheMode			= 8901,
	ERR_FileNotFound			= 8902,
	ERR_InvalidConfigFile		= 8903,
	
	ERR_UPNPDeviceNotLoaded		= 9000,
	ERR_DeviceNotOnline			= 9001,
	ERR_CantGetConnection		= 9002,
	ERR_ConnectTo				= 9003,
	
	ERR_DeviceHasNoEvents		= 9010,
	ERR_ServiceNameEmpty		= 9020,
	ERR_ServiceHasNoEvents		= 9021,
	Err_ServiceNotFound			= 9022,
	
	ERR_FunctionNotFound	  	= 9100,
	ERR_ParamIsEmpty			= 9101,
	ERR_InvalidParamTypeBool	= 9102,
	ERR_InvalidParamTypeNum		= 9103,
	ERR_InvalidParamTypeUint	= 9104,
	ERR_ValueToSmal				= 9105,
	ERR_ValueToBig				= 9106,
	ERR_ValueNotAllowed			= 9107;

const

	MSG_IN						= 20000,
	MSG_OUT						= 20001,
	MSG_PARAMS					= 20002,
	MSG_DESCRIPTION				= 20003,
	MSG_FUNCTION				= 20004;
	
?>